### ISSUE TITLE
実装する機能などの検討

### ISSUE THREAD

**Issue by conao** [conao/imgprocess3#1]
# 目的
実装する機能を検討し、v1.1のマイルストーンを作成する。

**Comment by conao** [comment]
話したところでは、
- 防犯カメラを作成する。
  - iphoneからリアルタイムで画像を取得し、

**Comment by NaoyaIijima** [comment]
話し合いの内容をまとめてくれてありがとう．
アイデアは特に思いついていないですが，思いついたら連絡します．

頑張って実装していきましょう！

**Comment by conao** [comment]
了解です。
とりあえずv1.1はこれで確定します。

v1.2についてまたアイデア等あればよろしくおねがいしますー！
